//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassiveInteractiveGraph.WebClient.DataProviderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataManagementNode", Namespace="http://schemas.datacontract.org/2004/07/MassiveInteractiveGraph.Services")]
    [System.SerializableAttribute()]
    public partial class DataManagementNode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataManagementLink", Namespace="http://schemas.datacontract.org/2004/07/MassiveInteractiveGraph.Services")]
    [System.SerializableAttribute()]
    public partial class DataManagementLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id1 {
            get {
                return this.Id1Field;
            }
            set {
                if ((this.Id1Field.Equals(value) != true)) {
                    this.Id1Field = value;
                    this.RaisePropertyChanged("Id1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id2 {
            get {
                return this.Id2Field;
            }
            set {
                if ((this.Id2Field.Equals(value) != true)) {
                    this.Id2Field = value;
                    this.RaisePropertyChanged("Id2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataProviderService.IDataProvider")]
    public interface IDataProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProvider/ListActiveNodes", ReplyAction="http://tempuri.org/IDataProvider/ListActiveNodesResponse")]
        System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementNode> ListActiveNodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProvider/ListActiveNodes", ReplyAction="http://tempuri.org/IDataProvider/ListActiveNodesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementNode>> ListActiveNodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProvider/ListActiveLinks", ReplyAction="http://tempuri.org/IDataProvider/ListActiveLinksResponse")]
        System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementLink> ListActiveLinks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProvider/ListActiveLinks", ReplyAction="http://tempuri.org/IDataProvider/ListActiveLinksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementLink>> ListActiveLinksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataProviderChannel : MassiveInteractiveGraph.WebClient.DataProviderService.IDataProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataProviderClient : System.ServiceModel.ClientBase<MassiveInteractiveGraph.WebClient.DataProviderService.IDataProvider>, MassiveInteractiveGraph.WebClient.DataProviderService.IDataProvider {
        
        public DataProviderClient() {
        }
        
        public DataProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementNode> ListActiveNodes() {
            return base.Channel.ListActiveNodes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementNode>> ListActiveNodesAsync() {
            return base.Channel.ListActiveNodesAsync();
        }
        
        public System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementLink> ListActiveLinks() {
            return base.Channel.ListActiveLinks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MassiveInteractiveGraph.WebClient.DataProviderService.DataManagementLink>> ListActiveLinksAsync() {
            return base.Channel.ListActiveLinksAsync();
        }
    }
}
