//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassiveInteractiveGraph.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.AdjacentNodes = new HashSet<Node>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Node> AdjacentNodes { get; set; }
    }
}
